[package]
name = "kovi-cli"
version = "0.3.3"
edition = "2021"
description = "kovi cli"
license = "MPL-2.0"
authors = ["Threkork <threkork@hotmail.com>"]
repository = "https://github.com/Threkork/Kovi"
readme = "README.md"
documentation = "https://threkork.github.io/kovi-doc/"

[dependencies]
clap = { version = "4.5", features = ["derive", "unstable-doc"] }
reqwest = { version = "0.12", features = ["blocking"] }
serde = { version = "1.0", features = ["derive"] }
colored = "2.1"
toml = { version = "0.8" }
serde_json = "1.0"
clap-cargo = "0.14"
crates_io_api = "0.11.0"


[[bin]]
name = "cargo-kovi"
path = "src/main.rs"
